project:
  name: quickstart-tableau-server
  owner: quickstart-eng@amazon.com
  package_lambda: false
  s3_regional_buckets: true
  shorten_stack_name: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  cluster-centos:
    parameters:
      AMIOS: CentOS-7-HVM
      AWSHostedZoneID: ''
      AWSPublicFQDN: ''
      AcceptEULA: 'yes'
      AvailabilityZones: $[alfred_getaz_3]
      ExistingSecurityGroup: ''
      IPAddress: ''
      InstanceType: m4.4xlarge
      KeyPairName: $[alfred_getkeypair]
      Password: $[alfred_genpass_32]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      SSLCertificateARN: ''
      SourceCIDR: 10.0.0.0/16
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: overridden
      Username: qsadmin
      WorkerCount: '2'
    regions:
    - us-east-1
    - eu-central-1
    s3_bucket: ''
    template: templates/tableau-cluster-linux-master.template
  cluster-ubuntu:
    parameters:
      AMIOS: Ubuntu-Server-16.04-LTS-HVM
      AWSHostedZoneID: ''
      AWSPublicFQDN: ''
      AcceptEULA: 'yes'
      AvailabilityZones: $[alfred_getaz_3]
      ExistingSecurityGroup: ''
      IPAddress: ''
      InstanceType: m4.4xlarge
      KeyPairName: $[alfred_getkeypair]
      Password: $[alfred_genpass_32]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      SSLCertificateARN: ''
      SourceCIDR: 10.0.0.0/16
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: overridden
      Username: qsadmin
      WorkerCount: '2'
    regions:
    - eu-west-1
    s3_bucket: ''
    template: templates/tableau-cluster-linux-master.template
#  cluster-windows:
#    parameters:
#      AWSHostedZoneID: ''
#      AWSPublicFQDN: ''
#      AvailabilityZones: $[alfred_getaz_3]
#      KeyPairName: $[alfred_getkeypair]
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3BucketRegion: $[taskcat_current_region]
#      RegCity: Test City
#      RegCompany: Test Company
#      RegCountry: Test Country
#      RegDepartment: Test Department
#      RegEmail: testemail@example.com
#      RegFirstName: Test First Name
#      RegIndustry: Test Industry
#      RegLastName: Test Last Name
#      RegPhone: Test Phone
#      RegState: Test State
#      RegTitle: Test Title
#      RegZip: Test Zip
#      SSLCertificateARN: ''
#      SourceCIDR: 10.0.0.0/16
#      TableauServerAdminPassword: $[alfred_genpass_32]
#      TableauServerAdminUser: admin
#      TableauServerLicenseKey: overridden
#    regions:
#    - us-east-2
#    - us-west-2
#    s3_bucket: ''
#    template: templates/tableau-cluster-windows-master.template
  single-centos:
    parameters:
      AMIOS: CentOS-7-HVM
      AcceptEULA: 'yes'
      AvailabilityZones: $[taskcat_genaz_2]
      InstanceType: m5.4xlarge
      KeyPairName: $[alfred_getkeypair]
      Password: $[alfred_genpass_32]
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      SourceCIDR: 0.0.0.0/0
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: ''
      Username: tsmadmin
      VPCCIDR: 10.0.0.0/16
    regions:
    - ap-northeast-1
    - ap-southeast-1
    - ca-central-1
    - us-west-1
    s3_bucket: ''
    template: templates/tableau-single-server-master.template
  single-ubuntu:
    parameters:
      AMIOS: Ubuntu-Server-16.04-LTS-HVM
      AcceptEULA: 'yes'
      AvailabilityZones: $[taskcat_genaz_2]
      InstanceType: m5.4xlarge
      KeyPairName: $[alfred_getkeypair]
      Password: $[alfred_genpass_32]
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-tableau-server/
      QSS3BucketRegion: $[taskcat_current_region]
      RegCity: Test City
      RegCompany: Test Company
      RegCountry: Test Country
      RegDepartment: Test Department
      RegEmail: testemail@example.com
      RegFirstName: Test First Name
      RegIndustry: Test Industry
      RegLastName: Test Last Name
      RegPhone: Test Phone
      RegState: Test State
      RegTitle: Test Title
      RegZip: Test Zip
      SourceCIDR: 0.0.0.0/0
      TableauServerAdminPassword: $[alfred_genpass_32]
      TableauServerAdminUser: admin
      TableauServerLicenseKey: ''
      Username: tsmadmin
      VPCCIDR: 10.0.0.0/16
    regions:
    - ap-northeast-2
    - us-east-1
    - us-west-2
    s3_bucket: ''
    template: templates/tableau-single-server-master.template
#  single-windows:
#    parameters:
#      AMIOS: Windows
#      AcceptEULA: 'yes'
#      AvailabilityZones: $[taskcat_genaz_2]
#      InstanceType: m5.4xlarge
#      KeyPairName: $[alfred_getkeypair]
#      Password: $[alfred_genpass_32]
#      PublicSubnet1CIDR: 10.0.128.0/20
#      PublicSubnet2CIDR: 10.0.144.0/20
#      QSS3BucketName: $[taskcat_autobucket]
#      QSS3KeyPrefix: quickstart-tableau-server/
#      QSS3BucketRegion: $[taskcat_current_region]
#      RegCity: Test City
#      RegCompany: Test Company
#      RegCountry: Test Country
#      RegDepartment: Test Department
#      RegEmail: testemail@example.com
#      RegFirstName: Test First Name
#      RegIndustry: Test Industry
#      RegLastName: Test Last Name
#      RegPhone: Test Phone
#      RegState: Test State
#      RegTitle: Test Title
#      RegZip: Test Zip
#      SourceCIDR: 0.0.0.0/0
#      TableauServerAdminPassword: $[alfred_genpass_32]
#      TableauServerAdminUser: admin
#      TableauServerLicenseKey: ''
#      Username: tsmadmin
#      VPCCIDR: 10.0.0.0/16
#    regions:
#    - ap-south-1
#    - ca-central-1
#    - eu-west-2
#    - us-east-2
#    s3_bucket: ''
#    template: templates/tableau-single-server-master.template
