global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-tableau-server
  regions:
    - ap-southeast-2
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true
tests:
  cluster:
    parameter_input: cluster.json
    template_file: tableau-cluster-master.template
